STAGE_1 = "1"

STAGE_2 = "2"

STAGE_3 = "3"

STAGE_DIVORCED = "DIVORCED"

STAGE_WIDOWED = "WIDOWED"

STAGE_5 = "5"

COMPLETE = "Complete"

STAGE_ORDER = [STAGE_1, STAGE_2, STAGE_3, STAGE_DIVORCED, STAGE_WIDOWED, STAGE_5, COMPLETE]