# Generated by Django 3.1.2 on 2020-11-25 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True, verbose_name='User Email')),
                ('has_liked', models.ManyToManyField(related_name='user_has_liked', to=settings.AUTH_USER_MODEL)),
                ('matched', models.ManyToManyField(related_name='user_has_matched_with', to=settings.AUTH_USER_MODEL)),
                ('was_liked', models.ManyToManyField(related_name='user_was_liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matrimonyapplication',
            name='connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.connection'),
        ),
    ]
