# Generated by Django 3.1.2 on 2020-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201125_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='user',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='User Email'),
        ),
    ]
