# Generated by Django 3.1.2 on 2020-12-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201130_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyapplication',
            name='interim_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyapplication',
            name='reg_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
