# Generated by Django 3.1.2 on 2020-12-03 13:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201202_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
