# Generated by Django 3.1.2 on 2020-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201203_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='addr_1',
            field=models.TextField(default='', null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='addr_2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address Line 2'),
        ),
    ]
