# Generated by Django 3.1.2 on 2020-12-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201210_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='pin_code',
            field=models.CharField(default='', max_length=8, null=True),
        ),
    ]
