# Generated by Django 3.1.2 on 2020-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201210_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyapplication',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Has been blocked by admin?'),
        ),
        migrations.AddField(
            model_name='matrimonyapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=30, null=True),
        ),
    ]
