# Generated by Django 3.1.2 on 2020-12-14 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20201214_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='has_blocked',
            field=models.ManyToManyField(related_name='has_blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='was_blocked',
            field=models.ManyToManyField(related_name='was_blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
