# Generated by Django 3.1.2 on 2020-12-19 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20201214_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='has_unliked',
            field=models.ManyToManyField(related_name='user_has_unliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='was_unliked',
            field=models.ManyToManyField(related_name='user_was_unliked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
