# Generated by Django 3.1.2 on 2020-12-20 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201219_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='User Email')),
                ('duration', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price')),
            ],
        ),
        migrations.AddField(
            model_name='matrimonyapplication',
            name='subs_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Subscription End Date'),
        ),
        migrations.AddField(
            model_name='matrimonyapplication',
            name='subs_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Subscription Start Date'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.plan')),
                ('user_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.matrimonyapplication')),
            ],
        ),
        migrations.AddField(
            model_name='matrimonyapplication',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.plan'),
        ),
    ]
