# Generated by Django 3.1.2 on 2020-12-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201220_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Plan Name'),
        ),
    ]
