# Generated by Django 3.1.2 on 2020-12-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_matrimonyapplication_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
