# Generated by Django 3.1.2 on 2020-12-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_receipt_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyapplication',
            name='is_settled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Has settled?'),
        ),
    ]
