# Generated by Django 3.1.2 on 2020-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_matrimonyapplication_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyapplication',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Paid User?'),
        ),
    ]
