# Generated by Django 3.1.2 on 2020-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201227_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, default='', null=True)),
                ('email', models.CharField(blank=True, default='User Email', max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='addr_1',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='city',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='country',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='state',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
