# Generated by Django 3.1.2 on 2021-01-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201228_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
