# Generated by Django 3.1.2 on 2020-12-30 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201228_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='date_of_death',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Date of Death of former spouse'),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='divorce_date',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Divorce Date'),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='marriage_annulment_date',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Marriage Annulment Date'),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='marriage_date_1',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Marriage Date'),
        ),
        migrations.AlterField(
            model_name='matrimonyapplication',
            name='marriage_date_2',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='Marriage Date'),
        ),
    ]
