# Generated by Django 3.1.2 on 2021-01-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210101_1832'),
        ('main', '0021_auto_20201230_1536'),
    ]

    operations = [
    ]
