# Generated by Django 3.1.2 on 2021-01-14 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_auto_20210101_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='has_blocked',
            field=models.ManyToManyField(blank=True, related_name='has_blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='has_liked',
            field=models.ManyToManyField(blank=True, related_name='user_has_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='has_unliked',
            field=models.ManyToManyField(blank=True, related_name='user_has_unliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='matched',
            field=models.ManyToManyField(blank=True, related_name='user_has_matched_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='was_blocked',
            field=models.ManyToManyField(blank=True, related_name='was_blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='was_liked',
            field=models.ManyToManyField(blank=True, related_name='user_was_liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='was_unliked',
            field=models.ManyToManyField(blank=True, related_name='user_was_unliked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
