# Generated by Django 3.1.2 on 2021-01-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210114_1821'),
        ('main', '0022_merge_20210101_1306'),
    ]

    operations = [
    ]
