# Generated by Django 3.1.2 on 2021-02-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_merge_20210114_1302'),
        ('main', '0024_auto_20210131_1940'),
    ]

    operations = [
    ]
