# Generated by Django 3.1.2 on 2021-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210131_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyapplication',
            name='migrated',
            field=models.BooleanField(default=True),
        ),
    ]
