# Generated by Django 3.1.2 on 2021-02-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_matrimonyapplication_migrated'),
        ('main', '0025_merge_20210201_1144'),
    ]

    operations = [
    ]
