# Generated by Django 3.1.2 on 2021-03-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_matrimonyapplication_migrated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetAndGreetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('meet_date', models.DateField(default=django.utils.timezone.now)),
                ('meet_slot', models.CharField(blank=True, choices=[('10-11', '10-11am'), ('11-12', '11-12am'), ('14-15', '2-3pm'), ('15-16', '3-4am'), ('16-17', '4-5am')], default='10-11', max_length=10)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('other_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_party', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
