# Generated by Django 3.1.2 on 2021-03-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210311_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetandgreetrequest',
            name='meet_slot',
            field=models.CharField(choices=[('10-11', '10-11am'), ('11-12', '11-12pm'), ('14-15', '2-3pm'), ('15-16', '3-4am'), ('16-17', '4-5am')], default='10-11', max_length=10),
        ),
    ]
