# Generated by Django 3.1.2 on 2021-03-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_merge_20210201_1259'),
        ('main', '0028_auto_20210312_1033'),
    ]

    operations = [
    ]
